name: Check PR title

on:
  pull_request:
    branches: [ 'master', 'develop', 'hotfix/*']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@v1.0.7
