name: Tests & Code Coverage

on:
  push:
    branches:
      - master
      - develop
      - "release/*"
  pull_request:
    branches:
      - develop
      - master
    types:
      - opened
      - synchronize

jobs:
  upload-code-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 10

      - name: Install Node.js Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
